export const REQUEST_MY_LIST = 'REQUEST_MY_LIST';
export const SUCCESS_MY_LIST = 'SUCCESS_MY_LIST';
export const ERROR_MY_LIST = 'ERROR_MY_LIST';

export const REQUEST_HOME_MOVIES = 'REQUEST_HOME_MOVIES';
export const SUCCESS_HOME_MOVIES = 'SUCCESS_HOME_MOVIES';
export const ERROR_HOME_MOVIES = 'ERROR_HOME_MOVIES';

export const REQUEST_CREATE_LIST = 'REQUEST_CREATE_LIST';
export const SUCCESS_CREATE_LIST = 'SUCCESS_CREATE_LIST';
export const ERROR_CREATE_LIST = 'ERROR_CREATE_LIST';